---
title: "Step 7"
date: 2018-10-29
---
title: Your awesome title is JoynerBrand
author: Bobby Joyner
email: joyner.bobby@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. "I'll do it tomarow."

# social links
twitter_username: your-twitter-handle
github_username:  JoynerBrand

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
